server:
  port: 8081

spring:
  application:
    name: zuul-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/business?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
zuul:
  retryable: true
  routes:
    authentication-service:
      path: /authentication/**
    upload-service:
      path: /upload/**
    company-service:
      path: /companyservice/**
    stockexchange-service:
      path: /stockexchangeservice/**
    user-service:
      path: /userservice/**

ribbon:
  eager-load:
    enabled: true
  ConnectTimeout: 4000
  ReadTimeout: 4000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000